### ISSUE TITLE
9993端口改不了

### ISSUE THREAD

**Issue by ppllpig** [LoganJinDev/zerotier-planet-moon#3]
为更改端口新建/var/lib/zerotier-one/local.conf添加
{
  "settings": {
    "primaryPort": 15559
  }
}
后，重启docker，端口依然9993
而遇到REQUESTING_CO。。错误又要删除/var/lib/zerotier-one/identity.*。删除后重启docker，local.conf文件又消失。。死循环

**Comment by ppllpig** [comment]
ZT_PRIMARY_PORT
这个变量哪里加？

**Comment by LoganJinDev** [comment]
更改端口号需要修改ztncui 、zerotier planet服务端、zerotier 客户端三处的配置
