### ISSUE TITLE
动态公网IP是否不支持自动切换IP的功能？

### ISSUE THREAD

**Issue by tianwulele** [LoganJinDev/zerotier-planet-moon#4]
S端--爱快--docker搭建  公网IP每晚定时重播更换动态IP【A地区的联通公网】
早上起来之后，发现
1.两台C端的windows开机可以直接连接，一台是B地区的公司电信无公网，一台C地区的家用联通有公网。
2.C地区的NAS之前重启过，重启之后没有自动接入S端，手动尝试加入失败
3.移动4G的手机，由于一直没有关机，也可以直连。退出VPN重新连接无法连接，手动尝试加入失败
4.C地区的openwrt没有重启，可以直连。
重新build planet后替换各个C端设备内的planet文件之后重连生效，换句话说是planet里面的文件是IP而不是动态域名，
请问是否支持动态域名替换IP呢？

**Comment by LoganJinDev** [comment]
暂时不支持动态公网IP自动切换

**Comment by tianwulele** [comment]
我有一个想法- -。。。
1.docker容器内添加定时功能，每天固定时间生成新的planet
2.openwrt内加入定时指令，自动更新planet并重启zeortier服务
3.同理，win10，nas也可以写个类似的定时，自动重启服务。
但是我的是爱快，无法通过宿主机来设定定时任务，请问这个镜像可以添加个类似的自动生成planet的功能嘛？  多谢多谢。感觉这样的话就算是动态IP也可以。

**Comment by LoganJinDev** [comment]
你说这些完全可以根据自己的需求写一个脚本来完成
