### ISSUE TITLE
搭建好之后  连接不上zerotier  页面也没有新设别接入的提示 

### ISSUE THREAD

**Issue by ABC15859888** [LoganJinDev/zerotier-planet-moon#5]
up  配置好之后  连接不上zerotier plant 网络  这是啥原因呢 
心里
![image](https://user-images.githubusercontent.com/38815757/220824340-ba1aa8c4-565b-45f9-84c0-a30db47871ed.png)

**Comment by LoganJinDev** [comment]
1.检查服务器端口9993 2.检查公网服务器自身 3.客户端版本建议使用1.10.1
